FROM node:22

WORKDIR /app

COPY package*.json ./
RUN npm install   # include dev deps (nodemon etc)

COPY src ./src

RUN useradd -m buttonwui
RUN mkdir -p /data && chown -R buttonwui:buttonwui /data /app

USER buttonwui

ENV NODE_ENV=development
EXPOSE 8192

CMD ["npm", "run", "dev"]
