FROM node:22

WORKDIR /app

COPY package*.json ./
RUN npm install   # include dev deps (nodemon etc)

COPY src ./src

RUN useradd -m envisalink
RUN mkdir -p /data && chown -R envisalink:envisalink /data /app

USER envisalink

ENV NODE_ENV=development
EXPOSE 8192

CMD ["npm", "run", "dev"]
